name: secure_counter
description: Example App for Amazon Cognito Identity SDK
  for Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.0"
  amazon_cognito_identity_dart_2: "^0.1.9"
  shared_preferences: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
