name: amazon_cognito_identity_dart_2
version: 0.1.25+2
homepage: https://github.com/furaiev/amazon-cognito-identity-dart-2
description: Unofficial Amazon Cognito Identity Provider Dart SDK, to add user
  sign-up / sign-in to your mobile and web apps with AWS Cloud Services. Based
  on amazon-cognito-identity-dart

dependencies:
  convert: ^2.1.1
  crypto: ^2.0.2+1
  http: ^0.12.1

dev_dependencies:
  pedantic: 1.9.2
  test: ^1.4.0

environment:
  sdk: ">=2.1.0 <3.0.0"
