name: amazon_cognito_identity_dart_2
version: 1.0.5
homepage: https://github.com/furaiev/amazon-cognito-identity-dart-2
description: Unofficial Amazon Cognito Identity Provider Dart SDK, to add user
  sign-up / sign-in to your mobile and web apps with AWS Cloud Services. Based
  on amazon-cognito-identity-dart

dependencies:
  convert: ^3.0.0
  crypto: ^3.0.0
  http: ^0.13.0
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.3

environment:
  sdk: '>=2.13.0 <3.0.0'
